<?php
session_start();
include("database.php");

if(!isset($_SESSION['client_id']) || !isset($_GET['payment_id'])){
    header("Location: paymentCL.php");
    exit();
}

$payment_id = intval($_GET['payment_id']);
$client_id = $_SESSION['client_id'];

// Get payment + project + client details
$query = "
    SELECT p.*, pr.Project_Name, pr.Project_Location, pr.Project_Value, c.Client_Name 
    FROM payment p 
    JOIN project pr ON p.Project_ID = pr.Project_ID 
    JOIN client c ON pr.Client_ID = c.Client_ID 
    WHERE p.Payment_ID = $payment_id AND pr.Client_ID = $client_id
";

$result = mysqli_query($conn, $query);
$row = mysqli_fetch_assoc($result);

if(!$row){
    die("<h2 style='color:red;text-align:center;margin-top:50px;'>Receipt not found or you don't have access.</h2>");
}

// Cegah access kalau status masih Pending
if(strtolower($row['Payment_Status']) !== 'completed'){
    die("<h2 style='color:orange;text-align:center;margin-top:50px;'>Receipt is not available. Payment is still Pending.</h2>");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receipt #<?php echo $row['Payment_ID']; ?> - DrillTech HDD</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(rgba(0, 48, 135, 0.45), rgba(15, 20, 30, 0.9)), 
                        url('backgroundCSC264.png') center/cover no-repeat fixed;
            color: #334155;
            min-height: 100vh;
        }

        .top-bar {
            background: #003087;
            padding: 12px 30px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            position: sticky;
            top: 0;
            z-index: 100;
            box-shadow: 0 4px 10px rgba(0,0,0,0.3);
        }
        
        .top-bar span { color: white; font-size: 16px; font-weight: 700; }
        
        .top-bar button {
            padding: 8px 18px;
            background: #ff8c00;
            color: white;
            border: none;
            border-radius: 6px;
            font-size: 13px;
            font-weight: 700;
            cursor: pointer;
            margin-left: 8px;
        }

        .report {
            max-width: 800px;
            margin: 40px auto;
            background: white;
            padding: 50px;
            border-radius: 8px;
            box-shadow: 0 10px 25px rgba(0,0,0,0.5);
        }

        .report-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #003087;
            padding-bottom: 20px;
            margin-bottom: 20px;
        }

        .company-name { font-size: 18px; font-weight: 800; color: #0f172a; }

        .report-title { font-size: 18px; font-weight: 800; color: #003087; }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        th, td {
            padding: 10px 12px;
            text-align: left;
            border-bottom: 1px solid #cbd5e1;
            font-size: 13.5px;
        }

        th { background: #f8fafc; color: #003087; font-weight: 700; }

        .highlight-row { background-color: #f1f5f9; font-weight: 700; }

        .footer {
            margin-top: 40px;
            font-size: 11px;
            color: #94a3b8;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
        }

        @media print {
            .top-bar { display: none; }
            .report { margin: 0; padding: 0; box-shadow: none; border: none; }
        }
    </style>
</head>
<body>

<div class="top-bar">
    <span>🔧 DRILLTECH — Official Payment Receipt</span>
    <div>
        <button onclick="window.print()">🖨 Print Receipt</button>
        <button onclick="window.history.back()" style="background:#7a7a7a;">✕ Back</button>
    </div>
</div>

<div class="report">
    <div class="report-header">
        <div>
            <img src="images/logo.png" alt="Logo" style="height:55px;" onerror="this.style.display='none';">
            <span class="company-name">DrillTech HDD Sdn. Bhd.</span>
        </div>
        <div>
            <span class="report-title">Official Receipt</span>
        </div>
    </div>

    <p style="font-size:13px; color:#64748b; margin-bottom:20px;">
        This receipt is officially generated by the DrillTech System.
    </p>

    <table>
        <tr><th>Detail Label</th><th>Information</th></tr>
        <tr><td><strong>Receipt No</strong></td><td>#<?php echo htmlspecialchars($row['Payment_ID']); ?></td></tr>
        <tr><td><strong>Client Name</strong></td><td><?php echo htmlspecialchars($row['Client_Name']); ?></td></tr>
        <tr><td><strong>Project Name</strong></td><td><?php echo htmlspecialchars($row['Project_Name']); ?></td></tr>
        <tr><td><strong>Project Location</strong></td><td><?php echo htmlspecialchars($row['Project_Location']); ?></td></tr>
        <tr><td><strong>Payment Date & Time</strong></td><td><?php echo htmlspecialchars($row['Payment_Date']) . " " . htmlspecialchars($row['Payment_Time']); ?></td></tr>
        <tr><td><strong>Payment Method</strong></td><td><?php echo htmlspecialchars($row['Payment_Method']); ?></td></tr>
        <tr><td><strong>Status</strong></td><td><strong style="color:green; text-transform:uppercase;"><?php echo htmlspecialchars($row['Payment_Status']); ?></strong></td></tr>
        <tr class="highlight-row"><td>Amount Paid (RM)</td><td><strong>RM <?php echo number_format($row['Project_Value'], 2); ?></strong></td></tr>
    </table>

    <div class="footer">
        DRILLTECH HDD Sdn. Bhd. &copy; All Rights Reserved.
    </div>
</div>

</body>
</html>